#!/bin/bash


cd laradockCourier

docker-compose up -d --force-recreate caddy php-fpm mysql phpmyadmin php-worker
docker-compose up -d workspace 

docker-compose exec workspace bash -e ./install/empty



